<a href="https://colab.research.google.com/github/chikum/models/blob/master/test_Confusion_Metrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# multilayer perceptron model for the two circles problem
from keras.models import Sequential
from keras.layers import Dense
from matplotlib import pyplot

# demonstration of calculating metrics for a neural network model using sklearn
from sklearn.datasets import make_circles
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# generate and prepare the dataset
def get_data():
	# generate dataset
	X, y = make_circles(n_samples=1000, noise=0.1, random_state=1)
	# split into train and test
	n_test = 500
	trainX, testX = X[:n_test, :], X[n_test:, :]
	trainy, testy = y[:n_test], y[n_test:]
	return trainX, trainy, testX, testy

In [ ]:
def get_model(trainX, trainy):
	# define model
	model = Sequential()
	model.add(Dense(100, input_dim=2, activation='relu'))
	model.add(Dense(1, activation='sigmoid'))
	# compile model
	model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
	# fit model
	model.fit(trainX, trainy, epochs=300, verbose=0)
	return model

In [ ]:
# generate data
trainX, trainy, testX, testy = get_data()
# fit model
model = get_model(trainX, trainy)
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 100)               300       
_________________________________________________________________
dense_19 (Dense)             (None, 1)                 101       
Total params: 401
Trainable params: 401
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# predict probabilities for test set
yhat_probs = model.predict(testX, verbose=0)
# predict crisp classes for test set
yhat_classes = model.predict_classes(testX, verbose=0)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
print(yhat_probs.shape)
print(yhat_classes.shape)

print(yhat_probs[:10])
print(yhat_classes[:10])


(500, 1)
(500, 1)
[[0.697662  ]
 [0.08872223]
 [0.38243788]
 [0.3809533 ]
 [0.50406647]
 [0.41641015]
 [0.2721169 ]
 [0.86081946]
 [0.58031696]
 [0.7709528 ]]
[[1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]]


In [ ]:
# reduce to 1d array
yhat_probs = yhat_probs[:, 0]
yhat_classes = yhat_classes[:, 0]

print(yhat_probs.shape)
print(yhat_classes.shape)


print(yhat_probs[:10])
print(yhat_classes[:10])
#print(testy[:10])

(500,)
(500,)
[0.697662   0.08872223 0.38243788 0.3809533  0.50406647 0.41641015
 0.2721169  0.86081946 0.58031696 0.7709528 ]
[1 0 0 0 1 0 0 1 1 1]


In [ ]:
print(testy.shape)
print(testy[:10])

(500,)
[1 0 0 0 0 0 0 1 1 0]


In [ ]:
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(testy, yhat_classes)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(testy, yhat_classes)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(testy, yhat_classes)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(testy, yhat_classes)
print('F1 score: %f' % f1)

Accuracy: 0.846000
Precision: 0.843137
Recall: 0.853175
F1 score: 0.848126


In [ ]:
# kappa
kappa = cohen_kappa_score(testy, yhat_classes)
print('Cohens kappa: %f' % kappa)
# ROC AUC
auc = roc_auc_score(testy, yhat_probs)
print('ROC AUC: %f' % auc)
# confusion matrix
print("Confusion Matrix")
matrix = confusion_matrix(testy, yhat_classes)
print(matrix)

Cohens kappa: 0.691951
ROC AUC: 0.924987
Confusion Matrix
[[208  40]
 [ 37 215]]
